name: SAMBIT KUMAR NAYAK's Art-Gallery React App Build

on:
  push:
    branches:
      - main  # Trigger on push to 'main' branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      # Optional: Upload build artifacts
      - name: Upload production build
        uses: actions/upload-artifact@v3
        with:
          name: production-build
          path: dist/

